# Dockerfile References: https://docs.docker.com/engine/reference/builder/

FROM ubuntu:20.04

# This deals with tzdata installation issues, but may not configure your VM timezone correctly.
# There are some potential work-arounds if that turns out to be a problem, but they didn't seem
# to be worth the trouble
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y apt-utils tzdata git vim gettext-base uuid-dev default-jre \
        bash autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev gawk \
        build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev \
        wget byacc device-tree-compiler python gtkwave python-yaml pkg-config swig python3-dev pip \
        virtualenv help2man tcl8.6-dev libreadline-dev libffi-dev \
        software-properties-common lsb-release
RUN apt-get install -y python-is-python3
RUN ln -nsf /usr/bin/tclsh8.6 /usr/bin/tclsh

# Update Cmake
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - > /etc/apt/trusted.gpg.d/kitware.gpg
RUN apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" \
    && apt-get update && apt-get install -y cmake

RUN apt-get clean

RUN pip install orderedmultidict

ARG USER_ID
ARG GROUP_ID

# Only create the group if it doesn't exist
RUN getent group $GROUP_ID || groupadd --gid $GROUP_ID build

# Use --no-log-init to deal with large userids creating giant log files
RUN useradd --no-log-init --uid $USER_ID --gid $GROUP_ID --shell /bin/bash --create-home build

LABEL maintainer="Mike Patnode <mike@mpsharp.com>"

USER build

WORKDIR /home/build/black-parrot-sim

ENTRYPOINT ["/bin/bash"]

